sudo: true

language: cpp

matrix:
  include:
    - os: linux
      addons:
        source:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

install:
  - sudo apt-get install cmake
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install gcc-4.9

script:
  - pwd
  - ls
  - cd ..
  - mkdir TBTKBuild
  - cd TBTKBuild
  - cmake ../TBTK/
  - make
  - sudo make instal
  - make test
