sudo: true

language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - sudo apt-get install cmake
  - sudo apt-get install libblas-dev liblapack-dev

env:
  - CC=gcc-4.9 && CXX=g++-4.9

script:
  - cd ..
  - mkdir TBTKBuild
  - cd TBTKBuild
  - cmake ../TBTK/
  - make
  - sudo make install
  - make
  - make test
