sudo: true

language: cpp

install:
  - sudo apt-get install cmake

script:
  - pwd
  - ls
  - cd ..
  - mkdir TBTKBuild
  - cd TBTKBuild
  - cmake ../TBTK/
  - make
  - sudo make instal
  - make test
