sudo: true

language: cpp

install:
  - sudo apt-get install cmake
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install gcc-4.9

script:
  - pwd
  - ls
  - cd ..
  - mkdir TBTKBuild
  - cd TBTKBuild
  - cmake ../TBTK/
  - make
  - sudo make instal
  - make test
